"""Named constants for neutral/default values, min/max ranges, and pipeline order."""

EXPOSURE_DEFAULT = 0.0
EXPOSURE_MIN = -5.0
EXPOSURE_MAX = 5.0
EXPOSURE_STEP = 0.05

CONTRAST_DEFAULT = 0.0
CONTRAST_MIN = -100.0
CONTRAST_MAX = 100.0
CONTRAST_STEP = 1.0

HIGHLIGHTS_DEFAULT = 0.0
HIGHLIGHTS_MIN = -100.0
HIGHLIGHTS_MAX = 100.0
HIGHLIGHTS_STEP = 1.0

SHADOWS_DEFAULT = 0.0
SHADOWS_MIN = -100.0
SHADOWS_MAX = 100.0
SHADOWS_STEP = 1.0

WHITES_DEFAULT = 0.0
WHITES_MIN = -100.0
WHITES_MAX = 100.0
WHITES_STEP = 1.0

BLACKS_DEFAULT = 0.0
BLACKS_MIN = -100.0
BLACKS_MAX = 100.0
BLACKS_STEP = 1.0

BRIGHTNESS_DEFAULT = 0.0
BRIGHTNESS_MIN = -100.0
BRIGHTNESS_MAX = 100.0
BRIGHTNESS_STEP = 1.0

SATURATION_DEFAULT = 0.0
SATURATION_MIN = -100.0
SATURATION_MAX = 100.0
SATURATION_STEP = 1.0

VIBRANCE_DEFAULT = 0.0
VIBRANCE_MIN = -100.0
VIBRANCE_MAX = 100.0
VIBRANCE_STEP = 1.0

TEMP_DEFAULT = 0.0
TEMP_MIN = -100.0
TEMP_MAX = 100.0
TEMP_STEP = 1.0

TINT_DEFAULT = 0.0
TINT_MIN = -100.0
TINT_MAX = 100.0
TINT_STEP = 1.0

HUE_DEFAULT = 0.0
HUE_MIN = -180.0
HUE_MAX = 180.0
HUE_STEP = 1.0

HSL_DEFAULT = 0.0
HSL_MIN = -100.0
HSL_MAX = 100.0
HSL_STEP = 1.0

SPLIT_TONING_HUE_DEFAULT = 0.0
SPLIT_TONING_HUE_MIN = 0.0
SPLIT_TONING_HUE_MAX = 360.0
SPLIT_TONING_HUE_STEP = 1.0

SPLIT_TONING_SAT_DEFAULT = 0.0
SPLIT_TONING_SAT_MIN = 0.0
SPLIT_TONING_SAT_MAX = 100.0
SPLIT_TONING_SAT_STEP = 1.0

SPLIT_TONING_BALANCE_DEFAULT = 0.0
SPLIT_TONING_BALANCE_MIN = -100.0
SPLIT_TONING_BALANCE_MAX = 100.0
SPLIT_TONING_BALANCE_STEP = 1.0

HSL_BAND_NAMES = ["red", "orange", "yellow", "green", "aqua", "blue", "purple", "magenta"]

PIPELINE_ORDER = [
    "whiteBalance",
    "exposure",
    "contrast",
    "highlights",
    "shadows",
    "whites",
    "blacks",
    "brightness",
    "hsl",
    "saturation",
    "vibrance",
    "splitToning",
    "curves",
    "sharpening",
    "noiseReduction",
    "vignette",
    "cropRotate",
]

PREVIEW_LONG_EDGE = 1920
